image:
  repository: ""
  tag: ""
  pullPolicy: "Always"
  repoKey: myregistrykey

nameOverride: ""
fullnameOverride: ""

replicas: 1

podAnnotations: {}

podSecurityContext: {}

ports: []

env: []

resources: {}

affinity: {}
tolerations: []

externalIntegrationKey: default-key

service:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  type: ClusterIP
